### PR TITLE
Replaced avatar.jpg with avatar.png

### PR DESCRIPTION
**Pull request by Strangehill**
just trying to be helpful but I'm new to git/github so please forgive any breach of etiquette.

### CODE REVIEW

**Comment by cobyism** [comment]
Thanks for the PR, and welcome to GitHub! ✨🎉

I’m not entirely sure what’s happened here, but if you look at [the current file in the `master` branch](https://github.com/cobyism/cobyism.github.io/blob/master/_includes/header.html#L3), it’s *already* using `.png`, and also has different dimensions (28px instead of 64px). It seems like this PR might be from an old version of the code or something? I had a quick look at the commit history, and honestly can’t explain why the diff is the way it is 😣, but I’m going to go ahead and close this PR since the change is already in effect.

**Comment by Strangehill** [comment]
the file you link to leads to the _includes/header file, which works great.
The file I committed is _layouts/post, which is why the bottom of your posts, where you've included an "about @cobyism section" you have a broken image

**Comment by cobyism** [comment]
Derp. You’re totally right. Thanks a ton for catching this (and even more :zap:s for fixing it for me)! :bow:

**Comment by Strangehill** [comment]
My pleasure! :bow:

**Pull request merged**
